# Generated by Django 3.1.1 on 2020-09-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job_experience',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='job_type',
            new_name='interest',
        ),
    ]
